// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieAppBackend.Data;

#nullable disable

namespace MovieAppBackend.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    [Migration("20240324053948_Assigned Primary Keys")]
    partial class AssignedPrimaryKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodBeveragePurchase", b =>
                {
                    b.Property<int>("foodBeveragesId")
                        .HasColumnType("int");

                    b.Property<int>("purchasesId")
                        .HasColumnType("int");

                    b.HasKey("foodBeveragesId", "purchasesId");

                    b.HasIndex("purchasesId");

                    b.ToTable("FoodBeveragePurchase");
                });

            modelBuilder.Entity("FoodBeverageTheater", b =>
                {
                    b.Property<int>("FoodBeveragesId")
                        .HasColumnType("int");

                    b.Property<int>("TheatersId")
                        .HasColumnType("int");

                    b.HasKey("FoodBeveragesId", "TheatersId");

                    b.HasIndex("TheatersId");

                    b.ToTable("FoodBeverageTheater");
                });

            modelBuilder.Entity("MovieAppBackend.Models.BookingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdultTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("ChildTicketQty")
                        .HasColumnType("int");

                    b.Property<string>("SelectedSeats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShowTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BookingInfos");
                });

            modelBuilder.Entity("MovieAppBackend.Models.FoodBeverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FoodBeverages");
                });

            modelBuilder.Entity("MovieAppBackend.Models.MovieItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("IMDBRating")
                        .HasColumnType("real");

                    b.Property<DateTime>("ScreeningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("MovieAppBackend.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingInfoId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingInfoId")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("MovieAppBackend.Models.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheaterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Theaters");
                });

            modelBuilder.Entity("MovieAppBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieItemTheater", b =>
                {
                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.Property<int>("theatersId")
                        .HasColumnType("int");

                    b.HasKey("MoviesId", "theatersId");

                    b.HasIndex("theatersId");

                    b.ToTable("MovieItemTheater");
                });

            modelBuilder.Entity("FoodBeveragePurchase", b =>
                {
                    b.HasOne("MovieAppBackend.Models.FoodBeverage", null)
                        .WithMany()
                        .HasForeignKey("foodBeveragesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieAppBackend.Models.Purchase", null)
                        .WithMany()
                        .HasForeignKey("purchasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodBeverageTheater", b =>
                {
                    b.HasOne("MovieAppBackend.Models.FoodBeverage", null)
                        .WithMany()
                        .HasForeignKey("FoodBeveragesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieAppBackend.Models.Theater", null)
                        .WithMany()
                        .HasForeignKey("TheatersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieAppBackend.Models.Purchase", b =>
                {
                    b.HasOne("MovieAppBackend.Models.BookingInfo", "BookingInfo")
                        .WithOne("Purchase")
                        .HasForeignKey("MovieAppBackend.Models.Purchase", "BookingInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingInfo");
                });

            modelBuilder.Entity("MovieItemTheater", b =>
                {
                    b.HasOne("MovieAppBackend.Models.MovieItem", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieAppBackend.Models.Theater", null)
                        .WithMany()
                        .HasForeignKey("theatersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieAppBackend.Models.BookingInfo", b =>
                {
                    b.Navigation("Purchase")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
